version: "3"
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.2.2
    hostname: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_AUTH=neo4j/password
  
  probableparser:
    container_name: probableparser
    build:
      context: ../
      dockerfile: docker-compose/Dockerfile
    depends_on: 
      - neo4j
    ports:
      - "8080:8080"